services:
  db:
    image: postgres:14.7
    volumes:
      - ${REGLIST_DB:-./tmp/db}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  taskrunner:
    build: .
    command: lambda_function.handler
    environment:
      DB_HOST: db
      DB_NAME: reglist_development
      DB_PASSWORD: password
      RECIPIENT: jeffrey.dettmann@gmail.com
    image: reglist-taskrunner
    volumes:
      - .:/app
    ports:
      - "9000:8080"
    depends_on:
      - db