version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  aws-ecr:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-ecr/build-and-push-image:
          repo: reglist-taskrunner

workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
          context:
            - AWSECR
