version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  aws-ecr:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/build-and-push-image:
          repo: reglist-taskrunner

workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
          context:
            - AWSECR
---
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
  build_and_push_image:
    jobs:
      -aws-ecr/build-and-push-image:
        repo: reglist-taskrunner